### PR TITLE
Add spotify feed

### PR DESCRIPTION
**Pull request by wey-gu**
and use modern badges

PS, for the Spotify URL, it takes hours to work

### CODE REVIEW

**Comment by wey-gu** [comment]
PS. it seems GitHub formatted the newline characters for me, thus end up many lines changed?

**Comment by wey-gu** [comment]
now I know i shouldnt modify the md file, working on it to change tql instead.

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
Please update README.tpl instead.

**Review by LinuxSuRen — APPROVED** [review]
LGTM

**Comment by wey-gu** [comment]
it's working now!

**Pull request merged**
