### PR TITLE
Add support to record events to Orbit

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Hold this PR until the meeting finished.

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
实际效果如下图所示：

image

**Comment by wey-gu** [comment]
I wonder how I was recognized as my previous employer;)
It comes from Tencent meeting or?

**Comment by LinuxSuRen** [comment]
> I wonder how I was recognized as my previous employer;)

I'm not sure about that. I can delete this screenshot if you don't want to show it in this PR.

**Comment by wey-gu** [comment]
No it's totally fine, just would like to address where I need to go to update my profile😆

**Comment by LinuxSuRen** [comment]
> No it's totally fine, just would like to address where I need to go to update my profile😆

Currently, the Orbit platform could fetch data from GitHub and Twitter. This might be helpful for you.

**Pull request merged**
